# This workflow will create a new tag if the version in Poetry is bigger than the current latest release.
name: Tag New Version If Updated
on:
  push:
    branches:
      - main

jobs:
  create-tag-if-new-version:
    # this workflow uses a token with expansive permissions, so we need to bind it to an environment
    # to make sure that that token can't be used in workflows not running on `main`
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Fetch current configured version
      id: current-version
      run: echo "::set-output name=version::$(poetry version -s)"

    - name: Fetch latest released version
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft

    - name: Create new tag for new version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        CUSTOM_TAG: ${{ steps.current-version.outputs.version }}
        RELEASE_BRANCHES: main
        VERBOSE: false
      if: steps.current-version.outputs.version != steps.latest-release.outputs.release
