# This workflow will create a new tag if the version in Poetry is bigger than the current latest release.
name: Tag New Version If Updated

on:
  push:
    branches:
      - main

jobs:
  create-tag-if-new-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1

    - name: Fetch current configured version
      id: current-version
      run: echo "::set-output name=version::$(poetry version -s)"

    - name: Fetch latest released version
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft

    - name: Create new tag for new version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.current-version.outputs.version }}
        RELEASE_BRANCHES: main

      if: steps.current-version.outputs.version != steps.latest-release.outputs.release
