name: Publish New Tag To Github and PyPI

on:
  - create

jobs:
  publish-release:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Check current recorded version in Poetry
      id: current-version
      run: echo "::set-output name=version::$(poetry version -s)"

    - name: Blow up if version does not match tag
      run: exit 1
      if: github.event.ref != steps.current-version.outputs.version

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      id: dependencies
      run: poetry install

    - name: Build library artifacts
      run: poetry build

    - name: Cut Github release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/broad_dagster_utils-*.tar.gz
          dist/broad_dagster_utils-*.whl

    - name: Push the library to PyPI
      run: poetry publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

