# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate Python

on:
  pull_request:
    branches:
      - main

jobs:
  python-validation:
    runs-on: ubuntu-latest
    env:
      ENV: test
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.DEV_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_TEST_KEY }}
        export_default_credentials: true
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-poetry
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      id: dependencies
      run: poetry install
    - name: Enforce coding style guide
      run: poetry run autopep8 --recursive --diff --exit-code .
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Install mypy requirements
      run: pip install types-python-dateutil types-pytz types-PyYAML
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Check static types
      run: poetry run mypy -p dagster_utils  --ignore-missing-imports --install-types --non-interactive
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Run test suite
      run: poetry run pytest
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
    - name: Run CI-only test suite
      run: pytest -m ci_only
      if: always() && steps.dependencies.outcome == 'success' # run all three checks, even if a prior check fails
